---
name: "PR: Cleanup"

on:
  pull_request:
    types:
      - closed

env:
  VERSION: PR-${{ github.event.pull_request.number }}

jobs:
  delete-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Delete release
        uses: nhatthm/gh-actions/github-delete-release@master
        with:
          release: ${{ env.VERSION }}

  delete-notification:
    runs-on: ubuntu-latest
    needs: [delete-image, delete-release]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Delete comment
        uses: nhatthm/gh-actions/github-one-comment@master
        with:
          body-include: "<!-- release-comment -->"
          delete: "true"
