---
name: "PR: Test and Release"

on:
  pull_request:

env:
  GO111MODULE: "on"
  VERSION: PR-${{ github.event.pull_request.number }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go-latest-version: ${{ steps.find-go-version.outputs.go-latest-version }}
      go-supported-versions: ${{ steps.find-go-version.outputs.go-supported-versions }}
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - id: find-go-version
        name: Find Go version
        uses: nhatthm/gh-actions/find-go-version@master

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        go-version: ${{ fromJson(needs.setup.outputs.go-supported-versions) }}
    runs-on: ${{ matrix.os }}
    needs: [setup]
    env:
      GO_LATEST_VERSION: ${{ needs.setup.outputs.go-latest-version }}
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Install Go
        uses: nhatthm/gh-actions/setup-go@master
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: |
          make test

      - name: Upload code coverage (unit)
        if: matrix.go-version == env.GO_LATEST_VERSION
        uses: nhatthm/gh-actions/codecov@master
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./unit.coverprofile
          flags: unittests-${{ runner.os }}

      #- name: Upload code coverage (features)
      #  if: matrix.go-version == env.GO_LATEST_VERSION
      #  uses: nhatthm/gh-actions/codecov@master
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    file: ./features.coverprofile
      #    flags: featurestests-${{ runner.os }}

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ darwin, linux, windows ]
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-latest
    needs: [test]
    env:
      GO_LATEST_VERSION: ${{ needs.setup.outputs.go-latest-version }}
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Setup
        run: |
          make "$GITHUB_ENV"

      - name: Install Go
        uses: nhatthm/gh-actions/setup-go@master
        with:
          go-version: ${{ env.GO_LATEST_VERSION }}

      - name: Build
        id: build
        run: |
          BUILD_NAME="authenticator-${VERSION}-${{ matrix.os }}-${{ matrix.arch }}"
          BUILD_DIR="out/${BUILD_NAME}"
          BUILD_DIR="${BUILD_DIR}/" VERSION="${VERSION}" GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make build

          echo "BUILD_NAME=${BUILD_NAME}" >> "$GITHUB_OUTPUT"
          echo "BUILD_DIR=${BUILD_DIR}" >> "$GITHUB_OUTPUT"

      - name: Upload Artifact
        uses: nhatthm/gh-actions/upload-artifact@master
        with:
          name: ${{ steps.build.outputs.BUILD_NAME }}
          path: ${{ steps.build.outputs.BUILD_DIR }}

  release-github:
    permissions:
      contents: write
      packages: write
    needs: [build]
    runs-on: ubuntu-latest
    env:
      GO_LATEST_VERSION: ${{ needs.setup.outputs.go-latest-version }}
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Download artifacts
        uses: nhatthm/gh-actions/download-artifact@master
        with:
          pattern: authenticator-*
          path: ${{ github.workspace }}/out

      - name: Packing
        run: |
          cd out/

          for i in ./*; do
            RELEASE=$(basename "${i}")

            echo "Packing binary for ${RELEASE}..."
            chmod +x "${RELEASE}/authenticator"
            tar -czf "${RELEASE}.tar.gz" "${RELEASE}"
          done

      - name: Delete release (${{ env.VERSION }})
        uses: nhatthm/gh-actions/github-delete-release@master
        with:
          release: ${{ env.VERSION }}

      - name: Release (${{ env.VERSION }})
        uses: nhatthm/gh-actions/github-release@master
        with:
          name: "${{ env.VERSION }}"
          tag_name: "${{ env.VERSION }}"
          draft: false
          prerelease: true
          files: "./out/*.tar.gz"
          body: |
            > [!CAUTION]
            > **!!! NOT READY FOR PRODUCTION !!!**
            >
            > This is a draft release for PR #${{ github.event.pull_request.number }}

            To test this release, run the following command:

            ```
            $ authenticator self-update ${{ env.VERSION }}
            ```

  send-notification:
    runs-on: ubuntu-latest
    needs: [release-github]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Comment
        uses: nhatthm/gh-actions/github-one-comment@master
        with:
          body-include: "<!-- release-comment -->"
          body: |
            <!-- release-comment -->

            Draft release with binaries included: [`${{ env.VERSION }}`](https://github.com/nhatthm/authenticator-cli/releases/tag/${{ env.VERSION }})

            To test this release, run the following command:

            ```
            $ authenticator self-update ${{ env.VERSION }}
            ```
